language: node_js
cache: yarn

os:
  - windows
  - linux
  - osx

node_js:
  - 8
  - 10
  - 12
  - node

env:
  global:
    - YARN_GPG=no
    - SNYK_TOKEN=18718bf9-b4b2-463f-b727-e9eb06e336bf
  matrix:
    - ZF_TRAVIS_COMMAND=test

matrix:
  include:
    - os: linux
      node_js: stable
      env: ZF_TRAVIS_COMMAND=test:javascript:browserstack

install: yarn --network-timeout 1000000
script: yarn run $ZF_TRAVIS_COMMAND

notifications:
  email: false
